# Helix言語サーバー設定

# Liquid (Shopify)
[[language]]
name = "liquid"
scope = "source.liquid"
file-types = ["liquid"]
comment-token = "{%"
language-servers = ["shopify-theme-check"]

[language-server.shopify-theme-check]
command = "shopify"
args = ["theme", "language-server"]

# Liquid grammar (tree-sitter)
[[grammar]]
name = "liquid"
source = { git = "https://github.com/hankthetank27/tree-sitter-liquid", rev = "main" }
